[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --tb=short --strict-markers"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "asyncio: marks tests as asyncio tests",
]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning",
    "ignore:coroutine .* was never awaited:RuntimeWarning",
]

# Ruff configuration is in .ruff.toml

[tool.pylint.MASTER]
# Note: pylint_per_file_ignores plugin may not be available in all CI environments

[tool.pylint.messages_control]
disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "duplicate-code",
    "too-many-positional-arguments",
    "too-many-public-methods",
    "protected-access",  # Disable globally since it's commonly needed in tests
    "too-many-lines",  # Disable for comprehensive test files
]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.design]
max-args = 7

[tool.coverage.run]
source = ["custom_components"]
omit = ["tests/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]
